defaults:
 - experiment: basic
    
experiment:
    repetitions: 10
    n_iterations: 150
    problem_names: ["ft06", "ft10", "ft20", "abz7", "abz8", "abz9", "la28", "la40"] #["la21", "la22", "la23", "la24", "la25", "la26", "la27", "la29"] 
    dump_population: False


quantum_hash_base_encoding: 
    _target_: qmea.QMEA
    _partial_: True
    activate_logging: True
    pop_object:
        _target_: qmea.QMEAPopulation
        N: 50
        reset_fraction: 0.1 # Clip the bottom % -> reset chromosomes back to 50/50
        activate_schedule: True
        decoding_method: "apply_operation_based_bierwirth"
        objectives: ["Makespan", "Mean Flow Time"]
        individual_type: QChromosomeHashMultisetImprovedEncoding #QChromosomeHashMultisetEncoding
        time_log: False
        rotation_angles: "[0.1*np.pi, 0, 0.02*np.pi, 0, 0.02*np.pi, 0, 0.1*np.pi, 0]" #"[0.1*np.pi, 0, 0.02*np.pi, 0, 0.02*np.pi, 0, 0.1*np.pi, 0]" # "[0.1*np.pi, 0, 0.05*np.pi, 0, 0.05*np.pi, 0, 0.1*np.pi, 0]"
        group_partitions: 8 # The number of partitions in the population
        individual_cfg:
            mutation_rate: 0
            reset_frequency: 3
