defaults:
- experiment: basic

experiment:
    repetitions: 10
    n_iterations: 150
    problem_names: ["ft06", "ft10", "ft20", "abz7", "abz8", "abz9", "la28", "la40"]
    experiment_id: 2
    dump_population: False
            

qmea_enhanced_random_key:  
    _target_: qmea.QMEA
    _partial_: True
    activate_logging: True
    pop_object:
        _target_: qmea.EnhancedQMEAPopulation
        N: 50
        reset_fraction: 0.1 # Clip the bottom quarter -> reset chromosomes back to 50/50
        activate_schedule: True
        decoding_method: "apply_operation_based_bierwirth"
        individual_type: EnhancedQuantumRandomKeyIndividual
        time_log: False
        rotation_angles: "[5, 0, 2, 0, 5, 0, 2, 0]" #"[0.2*np.pi, 0, 0.02*np.pi, 0, 0.02*np.pi, 0, 0.2*np.pi, 0]" #"[0.02*np.pi, 0, 0.05*np.pi, 0, 0.05*np.pi, 0, 0.02*np.pi, 0]"
        std_deltas: "[-0.3, -0.1, -0.3, -0.1]"
        group_partitions: 8
        individual_cfg: 
            start_std: 2
